## Tensori

Un tensore è una struttura dati particolare che generalizza quelle di array e matrici (array di array). Potremmo definirlo come un array multidimensionale. Ad esempio una immagine possiamo rappresentarla usando un tensore di ordine 3 perché abbiamo bisogno di 3 matrici ciascuna contenente il valore R, G, B di ciascun pixel. Possiamo immaginarlo come un insieme di matrici impilate una sopra l'altra, un vettore di matrici.
Quindi un tensore di ordine 4 possiamo vederlo come un vettore di tensori di ordine 3 (un vettore di matrici cubiche). L'ordine del tensore ci dice quanti parametri ci servono per identificare, localizzare un suo singolo elemento. Per un vettore abbiamo bisogno di un solo indice e dunque sarà un tensore di ordine 1 mentre per le matrici, avendo bisogno di due paramtri per localizzare un suo valore, esse saranno tensori di ordine 2. Per un tensore di ordine $k$ avremo bisogno di k parametri.

I tensori vengono utilizzati per rappresentare in forma numerica gli input, gli output e i parametri di un modello. I tensori rappresentano una forma adatta all'esecuzione su GPU ed altri ecceleratori hardware e per l'operazione di derivazione automatizzata.
Esistono diversi modi per creare un tensore in pytorch ad esempio direttamente a patire dai dati (un array multi-dimensionale) oppure da una array numpy oppure da un tensore esistente.
Ogni tensore pytorch è un oggetto della classe Tensor che descrive gli attributi di un tensore come shape (dimensioni), ed una serie di metodi che rappresentano operazioni eseguibili su di essi. Ogni tensore viene, per default, associato alla CPU ovvero tutte le operazioni su tensori vengono eseguite sulla CPU. E' possibile spostare l'esecuzione altrove, come ad esempio su di un acceleratore hardware (es. cuda), utilizzanto il metodo .to() che richiede l'oggetto Device rappresentativo dell'acceleratore.
E' possibile concatenare (joining) insieme una sequenza di tensori (due o più tensori) lungo una specificata dimensione utilizzando il metodo .cat()

In [3]:
# alcuni esempi
import torch

In [13]:
someData0 = [1, 2, 3, 4]
someData1 = [[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]
            ]
#uso di una funzione factory al posto del costruttore della classe tensor come consigliato
aTensor0 = torch.tensor(someData0)
aTensor1 = torch.tensor(someData1)

print(aTensor0)
print(f"Tensor0 size -> {aTensor0.size()}")
print("\n")
print(aTensor1)
print(f"Tensor1 size -> {aTensor1.size()}")

tensor([1, 2, 3, 4])
Tensor0 size -> torch.Size([4])


tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])
Tensor1 size -> torch.Size([4, 4])


In [14]:
#moltiplicazione righe per colonne fra tensori
res = aTensor0.matmul(aTensor1)
print(res)

tensor([ 90, 100, 110, 120])


In [20]:
# moltiplicazione elemento per elemento
aTensor0.multiply(torch.tensor([2, 3, 4, 5]))

tensor([ 2,  6, 12, 20])

In [29]:
# join di due tensori lungo due dimensioni distinte (per colonne e per righe)
t3 = torch.randint(100, (4, 4))
print(torch.cat([aTensor1, t3], dim=0))
print(torch.cat([aTensor1, t3], dim=1))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 7,  1, 82, 12],
        [55, 13, 17, 43],
        [44, 54, 64, 49],
        [17, 15, 17, 25]])
tensor([[ 1,  2,  3,  4,  7,  1, 82, 12],
        [ 5,  6,  7,  8, 55, 13, 17, 43],
        [ 9, 10, 11, 12, 44, 54, 64, 49],
        [13, 14, 15, 16, 17, 15, 17, 25]])
